// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shuffle_common_info.proto

package com.oppo.shuttle.rss.common;

public final class ShuffleInfo {
  private ShuffleInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MapShuffleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shuffle.MapShuffleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 mapId = 1;</code>
     * @return The mapId.
     */
    int getMapId();

    /**
     * <code>int64 attemptId = 2;</code>
     * @return The attemptId.
     */
    long getAttemptId();

    /**
     * <code>int32 shuffleWorkerGroupNum = 3;</code>
     * @return The shuffleWorkerGroupNum.
     */
    int getShuffleWorkerGroupNum();
  }
  /**
   * Protobuf type {@code shuffle.MapShuffleInfo}
   */
  public static final class MapShuffleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shuffle.MapShuffleInfo)
      MapShuffleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapShuffleInfo.newBuilder() to construct.
    private MapShuffleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapShuffleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MapShuffleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapShuffleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              mapId_ = input.readInt32();
              break;
            }
            case 16: {

              attemptId_ = input.readInt64();
              break;
            }
            case 24: {

              shuffleWorkerGroupNum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ShuffleInfo.internal_static_shuffle_MapShuffleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ShuffleInfo.internal_static_shuffle_MapShuffleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShuffleInfo.MapShuffleInfo.class, ShuffleInfo.MapShuffleInfo.Builder.class);
    }

    public static final int MAPID_FIELD_NUMBER = 1;
    private int mapId_;
    /**
     * <code>int32 mapId = 1;</code>
     * @return The mapId.
     */
    @java.lang.Override
    public int getMapId() {
      return mapId_;
    }

    public static final int ATTEMPTID_FIELD_NUMBER = 2;
    private long attemptId_;
    /**
     * <code>int64 attemptId = 2;</code>
     * @return The attemptId.
     */
    @java.lang.Override
    public long getAttemptId() {
      return attemptId_;
    }

    public static final int SHUFFLEWORKERGROUPNUM_FIELD_NUMBER = 3;
    private int shuffleWorkerGroupNum_;
    /**
     * <code>int32 shuffleWorkerGroupNum = 3;</code>
     * @return The shuffleWorkerGroupNum.
     */
    @java.lang.Override
    public int getShuffleWorkerGroupNum() {
      return shuffleWorkerGroupNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mapId_ != 0) {
        output.writeInt32(1, mapId_);
      }
      if (attemptId_ != 0L) {
        output.writeInt64(2, attemptId_);
      }
      if (shuffleWorkerGroupNum_ != 0) {
        output.writeInt32(3, shuffleWorkerGroupNum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mapId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mapId_);
      }
      if (attemptId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, attemptId_);
      }
      if (shuffleWorkerGroupNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, shuffleWorkerGroupNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ShuffleInfo.MapShuffleInfo)) {
        return super.equals(obj);
      }
      ShuffleInfo.MapShuffleInfo other = (ShuffleInfo.MapShuffleInfo) obj;

      if (getMapId()
          != other.getMapId()) return false;
      if (getAttemptId()
          != other.getAttemptId()) return false;
      if (getShuffleWorkerGroupNum()
          != other.getShuffleWorkerGroupNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAPID_FIELD_NUMBER;
      hash = (53 * hash) + getMapId();
      hash = (37 * hash) + ATTEMPTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAttemptId());
      hash = (37 * hash) + SHUFFLEWORKERGROUPNUM_FIELD_NUMBER;
      hash = (53 * hash) + getShuffleWorkerGroupNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ShuffleInfo.MapShuffleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShuffleInfo.MapShuffleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ShuffleInfo.MapShuffleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShuffleInfo.MapShuffleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ShuffleInfo.MapShuffleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shuffle.MapShuffleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shuffle.MapShuffleInfo)
        ShuffleInfo.MapShuffleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ShuffleInfo.internal_static_shuffle_MapShuffleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ShuffleInfo.internal_static_shuffle_MapShuffleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ShuffleInfo.MapShuffleInfo.class, ShuffleInfo.MapShuffleInfo.Builder.class);
      }

      // Construct using com.andes.ors2.common.ShuffleInfo.MapShuffleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mapId_ = 0;

        attemptId_ = 0L;

        shuffleWorkerGroupNum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ShuffleInfo.internal_static_shuffle_MapShuffleInfo_descriptor;
      }

      @java.lang.Override
      public ShuffleInfo.MapShuffleInfo getDefaultInstanceForType() {
        return ShuffleInfo.MapShuffleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public ShuffleInfo.MapShuffleInfo build() {
        ShuffleInfo.MapShuffleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ShuffleInfo.MapShuffleInfo buildPartial() {
        ShuffleInfo.MapShuffleInfo result = new ShuffleInfo.MapShuffleInfo(this);
        result.mapId_ = mapId_;
        result.attemptId_ = attemptId_;
        result.shuffleWorkerGroupNum_ = shuffleWorkerGroupNum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ShuffleInfo.MapShuffleInfo) {
          return mergeFrom((ShuffleInfo.MapShuffleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ShuffleInfo.MapShuffleInfo other) {
        if (other == ShuffleInfo.MapShuffleInfo.getDefaultInstance()) return this;
        if (other.getMapId() != 0) {
          setMapId(other.getMapId());
        }
        if (other.getAttemptId() != 0L) {
          setAttemptId(other.getAttemptId());
        }
        if (other.getShuffleWorkerGroupNum() != 0) {
          setShuffleWorkerGroupNum(other.getShuffleWorkerGroupNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ShuffleInfo.MapShuffleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ShuffleInfo.MapShuffleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mapId_ ;
      /**
       * <code>int32 mapId = 1;</code>
       * @return The mapId.
       */
      @java.lang.Override
      public int getMapId() {
        return mapId_;
      }
      /**
       * <code>int32 mapId = 1;</code>
       * @param value The mapId to set.
       * @return This builder for chaining.
       */
      public Builder setMapId(int value) {
        
        mapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mapId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMapId() {
        
        mapId_ = 0;
        onChanged();
        return this;
      }

      private long attemptId_ ;
      /**
       * <code>int64 attemptId = 2;</code>
       * @return The attemptId.
       */
      @java.lang.Override
      public long getAttemptId() {
        return attemptId_;
      }
      /**
       * <code>int64 attemptId = 2;</code>
       * @param value The attemptId to set.
       * @return This builder for chaining.
       */
      public Builder setAttemptId(long value) {
        
        attemptId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 attemptId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttemptId() {
        
        attemptId_ = 0L;
        onChanged();
        return this;
      }

      private int shuffleWorkerGroupNum_ ;
      /**
       * <code>int32 shuffleWorkerGroupNum = 3;</code>
       * @return The shuffleWorkerGroupNum.
       */
      @java.lang.Override
      public int getShuffleWorkerGroupNum() {
        return shuffleWorkerGroupNum_;
      }
      /**
       * <code>int32 shuffleWorkerGroupNum = 3;</code>
       * @param value The shuffleWorkerGroupNum to set.
       * @return This builder for chaining.
       */
      public Builder setShuffleWorkerGroupNum(int value) {
        
        shuffleWorkerGroupNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 shuffleWorkerGroupNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearShuffleWorkerGroupNum() {
        
        shuffleWorkerGroupNum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shuffle.MapShuffleInfo)
    }

    // @@protoc_insertion_point(class_scope:shuffle.MapShuffleInfo)
    private static final ShuffleInfo.MapShuffleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ShuffleInfo.MapShuffleInfo();
    }

    public static ShuffleInfo.MapShuffleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapShuffleInfo>
        PARSER = new com.google.protobuf.AbstractParser<MapShuffleInfo>() {
      @java.lang.Override
      public MapShuffleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapShuffleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapShuffleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapShuffleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ShuffleInfo.MapShuffleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shuffle_MapShuffleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shuffle_MapShuffleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031shuffle_common_info.proto\022\007shuffle\"Q\n\016" +
      "MapShuffleInfo\022\r\n\005mapId\030\001 \001(\005\022\021\n\tattempt" +
      "Id\030\002 \001(\003\022\035\n\025shuffleWorkerGroupNum\030\003 \001(\005B" +
      "$\n\025com.andes.ors2.commonB\013ShuffleInfob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shuffle_MapShuffleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shuffle_MapShuffleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shuffle_MapShuffleInfo_descriptor,
        new java.lang.String[] { "MapId", "AttemptId", "ShuffleWorkerGroupNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
